## Duration

Modified duration is the sensitivity of bond price on interest rate change.

bond PV = Coupon PV + Principal PV = $c \sum_{i=1}^{N} e^{-\frac{i}{m} r_i} + 100 e^{-\frac{N}{m} r_N}$

Where $r_n$ is zero rate

TODO: derive duration

## Treasury zero rate estimation using t-bond data

### t-bond data

In [3]:
from x01_data import parse_macroevent, bond_pricing

country = "KR"
df = parse_macroevent(f"x01_gvt_{country}.csv")

In [ ]:
## Bond Pricing. It uses B-bond auction price as market price of bond.

from dateutil import relativedelta
import pandas as pd 

df["Bond principal"] = 100
df["Maturity Date"] = [pd.to_datetime(x) for x in ["2027-09","2028-12","2030-09","2035-12","2045-09","2055-09","2074-09",]]
df["Issue Date"] = [(y - pd.offsets.DateOffset(years=x)) for x,y in df["Maturity Date"].items()]
df["Annual coupon"] = [x*2 for x in [2.250,2.750,2.500,3.250,2.750,2.625,2.750]]
df["TTM"] = df.apply(lambda x: relativedelta.relativedelta(x["Maturity Date"], x["Settle Date"]), axis=1).map(lambda x: x.years + x.months/12 + x.days / 360)
# Let's not forget to multiply 0.01
df["Bond price (Inferred)"] = df.apply(lambda x: bond_pricing(100, 2, 0.01 * x["Annual coupon"], 0.01 * x["Bond Yield"], x["Issue Date"], x["Maturity Date"], x["Settle Date"])[1], axis=1)

df

,Settle Date,Bond Yield,Bond principal,Maturity Date,Issue Date,Annual coupon,TTM,Bond price (Inferred)
Maturity,,,,,,,,
2,2025-12-01,2.876,100,2027-09-01,2025-09-01,4.50,1.750000,103.874850
3,2025-12-08,2.970,100,2028-12-01,2025-12-01,5.50,2.980556,107.270996
5,2025-12-22,3.245,100,2030-09-01,2025-09-01,5.00,4.694444,109.118230
10,2025-12-15,3.410,100,2035-12-01,2025-12-01,6.50,9.961111,126.159855
20,2025-12-23,3.365,100,2045-09-01,2025-09-01,5.50,19.691667,132.262560
30,2025-12-02,3.225,100,2055-09-01,2025-09-01,5.25,29.750000,139.871567
50,2025-12-12,3.140,100,2074-09-01,2024-09-01,5.50,48.722222,NaN

In [8]:
# Similar with Hull Table 4.3
df1 = df[["Bond principal", "TTM", "Annual coupon", "Bond price (Inferred)", "Bond Yield"]]
df1

,Bond principal,TTM,Annual coupon,Bond price (Inferred),Bond Yield
Maturity,,,,,
2,100,1.750000,4.50,103.874850,2.876
3,100,2.980556,5.50,107.270996,2.970
5,100,4.694444,5.00,109.118230,3.245
10,100,9.961111,6.50,126.159855,3.410
20,100,19.691667,5.50,132.262560,3.365
30,100,29.750000,5.25,139.871567,3.225
50,100,48.722222,5.50,NaN,3.140

### Bootstrap method 

In this example, some data is interpolated. 

The result can be improved by using more data, or better model

In [ ]:
# Let's use linear interopolation model to infer the zero rate curve from the data points.
# from scipy.interpolate import interp1d
class Interp1d:
    def __init__(self):
        self.xs:List[float] = []
        self.ys:List[float] = [] 
    def interpolate(self, x:float) -> float:
        return numpy.interp(x, self.xs, self.ys)
    def add_data(self, x:float, y:float):
        self.xs += [x]
        self.ys += [y]

def dates_into_year(d1, d2):
    assert(d1 < d2)
    x = relativedelta.relativedelta(d2, d1)
    return x.years + x.months/12 + x.days / 360

def get_coupon_dates(issue_date, maturity_date, freq):
    months = {1:12, 2:6, 4:3, 12:1}[freq]
    return pd.date_range(issue_date, maturity_date, freq=pd.DateOffset(months=months))[1:]

d0 = pd.to_datetime("2025-12-01") # starting date we set for the zero rate 

for i,x in df.iterrows(): # Bootstrap
    print(x)
    principal_amt = 100
    freq = 2 

    coupon_dates = get_coupon_dates(x["Issue Date"], x["Maturity Date"], freq=freq)
    coupon_amt = principal_amt * x["Annual coupon"] / freq

    coupon_dates_in_years = [dates_into_year(x["Settle Date"], y) for y in coupon_dates]
    print(coupon_dates)
    print(x["Settle Date"])
    print(coupon_dates_in_years)
    
    # x["Bond Yield"] is not continuous compounding version (it is based on acution notice document)
    # x["Bond Price"] = coupon_amt * np.sum(np.exp ( continuous_bond_yield -  * x["coupon_dates_in_years"] )) + principal_amt * np.exp ( continuous_bond_yield * x["coupon_dates_in_years"].iloc[-1] )


    # exp(-1/m y) + exp(-2/m y) + exp(-2/m y) ...  

    # x["TTM"]
    # x["Annual coupon"]

Settle Date              2025-12-01 00:00:00
Bond Yield                             2.876
Bond principal                           100
Maturity Date            2027-09-01 00:00:00
Issue Date               2025-09-01 00:00:00
Annual coupon                            4.5
TTM                                     1.75
Bond price (Inferred)              103.87485
Name: 2, dtype: object
DatetimeIndex(['2026-03-01', '2026-09-01', '2027-03-01', '2027-09-01'], dtype='datetime64[ns]', freq='<DateOffset: months=6>')
2025-12-01 00:00:00
[0.25, 0.75, 1.25, 1.75]
Settle Date              2025-12-08 00:00:00
Bond Yield                              2.97
Bond principal                           100
Maturity Date            2028-12-01 00:00:00
Issue Date               2025-12-01 00:00:00
Annual coupon                            5.5
TTM                                 2.980556
Bond price (Inferred)             107.270996
Name: 3, dtype: object
DatetimeIndex(['2026-06-01', '2026-12-01', '2027-06-01', '2027-12-01',
               '2028-06-01', '2028-12-01'],
              dtype='datetime64[ns]', freq='<DateOffset: months=6>')
2025-12-08 00:00:00
[0.48333333333333334, 0.9805555555555555, 1.4833333333333334, 1.9805555555555554, 2.4833333333333334, 2.980555555555555]
Settle Date              2025-12-22 00:00:00
Bond Yield                             3.245
Bond principal                           100
Maturity Date            2030-09-01 00:00:00
Issue Date               2025-09-01 00:00:00
Annual coupon                            5.0
TTM                                 4.694444
Bond price (Inferred)              109.11823
Name: 5, dtype: object
DatetimeIndex(['2026-03-01', '2026-09-01', '2027-03-01', '2027-09-01',
               '2028-03-01', '2028-09-01', '2029-03-01', '2029-09-01',
               '2030-03-01', '2030-09-01'],
              dtype='datetime64[ns]', freq='<DateOffset: months=6>')
2025-12-22 00:00:00
[0.18611111111111112, 0.6944444444444444, 1.1861111111111111, 1.6944444444444442, 2.1888888888888887, 2.694444444444444, 3.186111111111111, 3.694444444444444, 4.186111111111112, 4.694444444444445]
Settle Date              2025-12-15 00:00:00
Bond Yield                              3.41
Bond principal                           100
Maturity Date            2035-12-01 00:00:00
Issue Date               2025-12-01 00:00:00
Annual coupon                            6.5
TTM                                 9.961111
Bond price (Inferred)             126.159855
Name: 10, dtype: object
DatetimeIndex(['2026-06-01', '2026-12-01', '2027-06-01', '2027-12-01',
               '2028-06-01', '2028-12-01', '2029-06-01', '2029-12-01',
               '2030-06-01', '2030-12-01', '2031-06-01', '2031-12-01',
               '2032-06-01', '2032-12-01', '2033-06-01', '2033-12-01',
               '2034-06-01', '2034-12-01', '2035-06-01', '2035-12-01'],
              dtype='datetime64[ns]', freq='<DateOffset: months=6>')
2025-12-15 00:00:00
[0.4638888888888889, 0.961111111111111, 1.463888888888889, 1.961111111111111, 2.4638888888888886, 2.961111111111111, 3.4638888888888886, 3.961111111111111, 4.4638888888888895, 4.961111111111111, 5.4638888888888895, 5.961111111111111, 6.4638888888888895, 6.961111111111111, 7.4638888888888895, 7.961111111111111, 8.463888888888889, 8.96111111111111, 9.463888888888889, 9.96111111111111]
Settle Date              2025-12-23 00:00:00
Bond Yield                             3.365
Bond principal                           100
Maturity Date            2045-09-01 00:00:00
Issue Date               2025-09-01 00:00:00
Annual coupon                            5.5
TTM                                19.691667
Bond price (Inferred)              132.26256
Name: 20, dtype: object
DatetimeIndex(['2026-03-01', '2026-09-01', '2027-03-01', '2027-09-01',
               '2028-03-01', '2028-09-01', '2029-03-01', '2029-09-01',
               '2030-03-01', '2030-09-01', '2031-03-01', '2031-09-01',
               '2032-03-01', '2032-09-01', '2033-03-01', '2033-09-01',
               '2034-03-01', '2034-09-01', '2035-03-01', '2035-09-01',
               '2036-03-01', '2036-09-01', '2037-03-01', '2037-09-01',
               '2038-03-01', '2038-09-01', '2039-03-01', '2039-09-01',
               '2040-03-01', '2040-09-01', '2041-03-01', '2041-09-01',
               '2042-03-01', '2042-09-01', '2043-03-01', '2043-09-01',
               '2044-03-01', '2044-09-01', '2045-03-01', '2045-09-01'],
              dtype='datetime64[ns]', freq='<DateOffset: months=6>')
2025-12-23 00:00:00
[0.18333333333333332, 0.6916666666666667, 1.1833333333333333, 1.6916666666666664, 2.186111111111111, 2.6916666666666664, 3.183333333333333, 3.6916666666666664, 4.183333333333334, 4.691666666666667, 5.183333333333334, 5.691666666666667, 6.186111111111112, 6.691666666666667, 7.183333333333334, 7.691666666666667, 8.183333333333334, 8.691666666666666, 9.183333333333334, 9.691666666666666, 10.18611111111111, 10.691666666666666, 11.183333333333334, 11.691666666666666, 12.183333333333334, 12.691666666666666, 13.183333333333334, 13.691666666666666, 14.18611111111111, 14.691666666666666, 15.183333333333334, 15.691666666666666, 16.183333333333334, 16.691666666666666, 17.183333333333334, 17.691666666666666, 18.186111111111114, 18.691666666666666, 19.183333333333334, 19.691666666666666]
Settle Date              2025-12-02 00:00:00
Bond Yield                             3.225
Bond principal                           100
Maturity Date            2055-09-01 00:00:00
Issue Date               2025-09-01 00:00:00
Annual coupon                           5.25
TTM                                    29.75
Bond price (Inferred)             139.871567
Name: 30, dtype: object
DatetimeIndex(['2026-03-01', '2026-09-01', '2027-03-01', '2027-09-01',
               '2028-03-01', '2028-09-01', '2029-03-01', '2029-09-01',
               '2030-03-01', '2030-09-01', '2031-03-01', '2031-09-01',
               '2032-03-01', '2032-09-01', '2033-03-01', '2033-09-01',
               '2034-03-01', '2034-09-01', '2035-03-01', '2035-09-01',
               '2036-03-01', '2036-09-01', '2037-03-01', '2037-09-01',
               '2038-03-01', '2038-09-01', '2039-03-01', '2039-09-01',
               '2040-03-01', '2040-09-01', '2041-03-01', '2041-09-01',
               '2042-03-01', '2042-09-01', '2043-03-01', '2043-09-01',
               '2044-03-01', '2044-09-01', '2045-03-01', '2045-09-01',
               '2046-03-01', '2046-09-01', '2047-03-01', '2047-09-01',
               '2048-03-01', '2048-09-01', '2049-03-01', '2049-09-01',
               '2050-03-01', '2050-09-01', '2051-03-01', '2051-09-01',
               '2052-03-01', '2052-09-01', '2053-03-01', '2053-09-01',
               '2054-03-01', '2054-09-01', '2055-03-01', '2055-09-01'],
              dtype='datetime64[ns]', freq='<DateOffset: months=6>')
2025-12-02 00:00:00
[0.24166666666666664, 0.75, 1.2416666666666667, 1.7499999999999998, 2.2444444444444445, 2.75, 3.2416666666666667, 3.75, 4.241666666666667, 4.75, 5.241666666666667, 5.75, 6.2444444444444445, 6.75, 7.241666666666667, 7.75, 8.241666666666665, 8.75, 9.241666666666665, 9.75, 10.244444444444444, 10.75, 11.241666666666665, 11.75, 12.241666666666665, 12.75, 13.241666666666665, 13.75, 14.244444444444444, 14.75, 15.241666666666665, 15.75, 16.241666666666667, 16.75, 17.241666666666667, 17.75, 18.244444444444447, 18.75, 19.241666666666667, 19.75, 20.241666666666667, 20.75, 21.241666666666667, 21.75, 22.244444444444447, 22.75, 23.241666666666667, 23.75, 24.241666666666667, 24.75, 25.241666666666667, 25.75, 26.244444444444447, 26.75, 27.241666666666667, 27.75, 28.241666666666667, 28.75, 29.241666666666667, 29.75]
Settle Date              2025-12-12 00:00:00
Bond Yield                              3.14
Bond principal                           100
Maturity Date            2074-09-01 00:00:00
Issue Date               2024-09-01 00:00:00
Annual coupon                            5.5
TTM                                48.722222
Bond price (Inferred)                    NaN
Name: 50, dtype: object

AssertionError: